### ISSUE TITLE
how was data in data dir produced?

### ISSUE THREAD

**Issue by gchaperon** [ASSERT-KTH/sequencer#27]
Hi!

How was the data from /data dir produced?
I am mainly interested in `src-{train,val,test}.txt`, I would imagine the other ones are truncated versions of these.
I see these have been already tokenized and preprocessed, and the `<START_BUG>` and `<END_BUG>` tokens have been added.

Best!
Gabriel.

**Comment by chenzimin** [comment]
Hi Grbriel,

A lot of processing steps can be seen in https://github.com/KTH/chai/blob/master/src/sequencer-predict.sh, ie. we create the abstract buggy context, then tokenize it, then truncate to 1000 tokens. And that is done for all the examples in src-{train,val,test}.txt

**Comment by gchaperon** [comment]
hi,

so you just take all data from https://github.com/KTH/CodRep-competition and perform the preprocessing pipeline on those? where can i get the data from bugs2fix?
looking online i found this https://sites.google.com/view/learning-fixes/data (i got there from the paper you cite), is that correct? how did you preprocess those? I read from the paper that you only kept one-line bug fixes (to comply with sequencer's data format), but i was wondering if i could take a look at the code used.

best!
Gabriel.

**Comment by chenzimin** [comment]
Hi Gabriel,

The data from from bugs2fix was sent to me by the authors, so I don't know if it is exactly the same as https://sites.google.com/view/learning-fixes/data.

As for only keeping the one-line bugs fixes, I did a small filtering step with `python-unidiff` to only keep one line replacement patches. Then I used [gumtree-spoon-ast-diff](https://github.com/SpoonLabs/gumtree-spoon-ast-diff) to only keep changes that changed a line inside a function. You can see this step [here](https://github.com/KTH/chai/blob/master/src/Buggy_Context_Abstraction/abstraction/src/main/java/se/kth/methodWithClassContextAbstraction.java#L106).
