### ISSUE TITLE
Cannot locate buggy line for some bugs

### ISSUE THREAD

**Issue by claudeyj** [ASSERT-KTH/sequencer#44]
Hi Dr. Chen, your tool is very elegant and helpful! But I found one issue in the preprocessing phase and hope to confirm that with you. The context is that I'm using SequenceR to generate patches for new bugs. I notice that you have a `Buggy_Context_Abstraction/tokenize.py` script to tokenize the abstraction file. In the abstraction file you attempted to tag the buggy line with a comment line "// ONLY FOR TOKENIZATION, BUGGY LINE BELOW" right before it. Then in the `tokenize.py` you use that tag to get the buggy line. But for some cases, the comment line will be added right after the previous statement instead of  in the new line after the previous statement. Therefore when `tokenize.py` tries to recognize this tag, it will fail. I think that's an internal issue of the `abstraction` Java library. But it should be easy to fix this issue by either fixing the Java lib or adding a patch to handle corner cases of `tokenize.py`. Thank you for reading this.

**Comment by chenzimin** [comment]
But I agree that this step should be improved, e.g. if we just save the line number somewhere else.

**Comment by claudeyj** [comment]
Hi Dr. Chen, thanks a lot for your reply. I've created a PR [https://github.com/KTH/sequencer/pull/46](url) and please kindly check it!
