### ISSUE TITLE
Get top level method failure

### ISSUE THREAD

**Issue by claudeyj** [ASSERT-KTH/sequencer#45]
Hi Dr. Chen, I found there could be an issue in the `Abstraction` Java library. The context is that I'm using SequenceR for generating patches for some new bugs. In most cases it's very powerful but for some cases it could fail due to early termination in abstraction stage. https://github.com/KTH/sequencer/blob/3171280dc5a47f8cc0e4bdd9fee45f4e9a77fd88/src/Buggy_Context_Abstraction/abstraction/src/main/java/se/kth/methodWithClassContextAbstraction.java#L104 tries to get the top level method of the buggy element but for some cases it returns null (where actually it should not be). Note that these cases are not rare so fixing this issue could lead to more bugs to be fixed and the robustness of SequenceR to be improved.

**Comment by claudeyj** [comment]
Hi Dr. Chen, here is a minimal example:

WORK_DIR=/tmp
SEQUENCER_DIR=/absolute/path/to/sequencer
cd $WORK_DIR
defects4j checkout -p Chart -v 1f -w Chart_1f
mkdir output
$SEQUENCER_DIR/src/sequencer-predict.sh --model=$SEQUENCER_DIR/model/model.pt --buggy_file=/tmp/Chart_1f/source/org/jfree/chart/axis/PeriodAxis.java --buggy_line=238 --beam_size=100 --output=/tmp/output

And here is the console message:
sequencer-predict.sh start
Input parameter:
BUGGY_FILE_PATH = /home/jun/research/dlapr/sequencer/tmp/chart21532.java
BUGGY_LINE = 238
BEAM_SIZE = 100
OUTPUT = /home/jun/research/dlapr/sequencer/tmp/output_chart21532

Creating temporary working folder
/home/jun/research/dlapr/sequencer/src/tmp

Abstracting the source file
Buggy ctElement is not inside of CtMethod
Cannot generate abstraction for the buggy file

Thank you again for taking a look!

**Comment by claudeyj** [comment]
It looks like all the failing cases I checked are trying to get the top level method of a statement in a constructor method.

**Comment by claudeyj** [comment]
Hi Dr. Chen, sorry for bothering you again, do you have some ideas on this bug? I would appreciate it a lot if you can take a look. Thank you!

**Comment by claudeyj** [comment]
I see, thanks for your response! I agree with you that it's kind of out of the scope of SequenceR to fix, but fundamentally the scope is a bit limited by the dependent library so it should not be hard to extend the scope as you mentioned and enable SequenceR to fix even more bugs (I remember there are truly some Defects4J bugs in constructors).

**Comment by monperrus** [comment]
Fixed in https://github.com/ASSERT-KTH/sequencer/pull/48

@claudeyj could you give it a try with branch `getTopLevelConstructor` and let us know if it works?

@chenzimin could you review https://github.com/ASSERT-KTH/sequencer/pull/48?

thanks!

**Comment by claudeyj** [comment]
> Fixed in #48
> 
> @claudeyj could you give it a try with branch `getTopLevelConstructor` and let us know if it works?
> 
> @chenzimin could you review #48?
> 
> thanks!

Thanks a lot for the fix! I'll try that.
